export const FETCH_INIT_MENU_DATA = 'FETCH_INIT_MENU_DATA';
export const FETCH_INIT_HOME_DATA = 'FETCH_INIT_HOME_DATA';
export const FETCH_INIT_HOME_ELEMENTS_DATA = 'FETCH_INIT_HOME_ELEMENTS_DATA';
export const FETCH_INIT_TOOLS_AND_TECH_DATA = 'FETCH_INIT_TOOLS_AND_TECH_DATA';
export const FETCH_INIT_PORTFOLIO_DATA = 'FETCH_INIT_PORTFOLIO_DATA';
export const FETCH_INIT_GALLERY_DATA = 'FETCH_INIT_GALLERY_DATA';